import test from 'node:test';
import assert from 'node:assert/strict';
import {FRAMES,MS,analyze,candles,rsi} from '../public/engine.js';
import worker from '../src/worker.js';
const now=1800000000000+5000;
function fixture(seed=1){let state=seed;const rand=()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/2**32);return Object.fromEntries(FRAMES.map(f=>{let p=100;const end=Math.floor(now/MS[f])*MS[f];return [f,Array.from({length:180},(_,i)=>{const o=p;p+=.08+(rand()-.5)*.8;return [end-(180-i)*MS[f],o,Math.max(o,p)+rand()*.4,Math.min(o,p)-rand()*.4,p,100+rand()*50,end-(179-i)*MS[f]-1];})];}));}
const meta={symbol:'TESTUSDT',market:'usd',volume:5e7,tick:.001};
test('RSI flat, rising and falling boundaries',()=>{assert.equal(rsi(Array(40).fill(10)),50);assert.equal(rsi(Array.from({length:40},(_,i)=>i)),100);assert.equal(rsi(Array.from({length:40},(_,i)=>40-i)),0);});
test('open future candles never enter analysis',()=>{const data=fixture();const before=analyze(data,meta,{},now);data['5m'].push([now,1,1e9,0,1e9,1e9,now+300000]);assert.deepEqual(analyze(data,meta,{},now),before);assert.equal(candles(data['5m'],now).length,180);});
test('reject incomplete and expired market data',()=>{const data=fixture();assert.equal(analyze({...data,'1d':[]},meta,{},now).status,'INSUFFICIENT');assert.equal(analyze(data,meta,{},now+600000).status,'STALE');});
function trendFixture(dir){return Object.fromEntries(FRAMES.map(f=>{const end=Math.floor(now/MS[f])*MS[f];return [f,Array.from({length:180},(_,i)=>{let c=100+i*.05;if(i===40)c=125;if(i===178)c-=.1;let o=c-.04,h=c+.25,l=c-.15;if(dir<0)[o,h,l,c]=[200-o,200-l,200-h,200-c];return [end-(180-i)*MS[f],o,h,l,c,100,end-(179-i)*MS[f]-1]})]}));}
test('both long and short setups have directional stops, ordered targets and net RR',()=>{for(const dir of [1,-1]){const data=trendFixture(dir);const result=analyze(data,meta,{},now);assert.ok(result.plan,JSON.stringify(result.reasons));assert.equal(result.status,dir===1?'BUY':'SELL');const p=result.plan;assert.ok(dir*(p.entry-p.stop)>0);assert.ok(p.targets.every(x=>dir*(x-p.entry)>0));assert.ok(dir*(p.targets[2]-p.targets[1])>0);assert.ok(p.netRR>=2);assert.equal(analyze(data,{...meta,volume:0},{},now).plan,null);assert.equal(analyze(data,meta,{feeBps:10000},now).plan,null);}});
test('worker rejects arbitrary proxy destinations and invalid symbols',async()=>{for(const path of ['/api/anything','/api/klines?symbol=../../bad&interval=5m','/api/time?market=other']){const r=await worker.fetch(new Request('https://test'+path),{},{});assert.ok(r.status>=400);}});
test('worker sends bounded closed-candle requests and preserves upstream blocks',async()=>{const original=globalThis.fetch;let url;try{globalThis.fetch=async u=>{url=new URL(u);return Response.json([]);};const r=await worker.fetch(new Request('https://test/api/klines?symbol=BTCUSDT&interval=5m'),{},{});assert.equal(r.status,200);assert.equal(url.hostname,'fapi.binance.com');assert.equal(url.searchParams.get('limit'),'180');assert.ok(+url.searchParams.get('endTime')<Date.now());globalThis.fetch=async()=>new Response('',{status:451});const blocked=await worker.fetch(new Request('https://test/api/time'),{},{});assert.equal(blocked.status,451);assert.match((await blocked.json()).error,/location-restricted/);}finally{globalThis.fetch=original;}});
